config/routes.rb
ProspectEvaluator::Application.routes.draw do
  resources :players

  root 'players#index'

end

app/models/news.rb
require 'open-uri'

class News < ActiveRecord::Base
    belongs_to :player
    validates :url, uniqueness: true

    def scrape_html
        begin
            html = open(self.url).read()
            body = Pismo::Document.new(html).body
            self.update_attributes(:html => html, :body => body)
        rescue
            self.destroy
        end
    end
end

app/models/player.rb
class Player < ActiveRecord::Base
    has_many :news
    has_many :tweets
    has_many :tweet_abouts

    def keyword_array
        eval(keywords.gsub("(u", "[").gsub(")", "]").gsub("(", "["))
    end

    def get_color(number)
        number >= 0 ? "Green" : "Red"
    end

    def get_sign(number)
        number >= 0 ? "+" : ""
    end
end

app/models/tweet.rb
require 'sentimental'

class Tweet < ActiveRecord::Base
    belongs_to :player
    validates :tweet_id, uniqueness: true
end

app/models/tweet_about.rb
require 'sentimental'

class TweetAbout < ActiveRecord::Base
    belongs_to :player
    validates :tweet_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @news = @player.news
    @tweets = @player.tweets
    @tweet_abouts = @player.tweet_abouts
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :position, :hometown, :college_class, :reach, :wingspan, :age, :date_of_birth, :college, :height, :weight, :photo_url, :espn_overall_rank, :espn_position_rank)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProspectEvaluator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :position, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :position, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hometown, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hometown, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :college_class, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :college_class, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reach, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reach, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :wingspan, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :wingspan, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date_of_birth, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date_of_birth, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :college, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :college, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :height, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :height, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :weight, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weight, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :espn_overall_rank, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :espn_overall_rank, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :espn_position_rank, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :espn_position_rank, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>2015 NBA Draft Class</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:hometown) %></th>
      <th><%= model_class.human_attribute_name(:college_class) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:college) %></th>
      <th><%= model_class.human_attribute_name(:espn_overall_rank) %></th>
      <th><%= model_class.human_attribute_name(:espn_position_rank) %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= image_tag player.photo_url %></td>
        <td><%= link_to player.name, player_path(player) %></td>
        <td><%= player.position %></td>
        <td><%= player.hometown %></td>
        <td><%= player.college_class %></td>
        <td><%= player.age %></td>
        <td><%= player.college %></td>
        <td><%= player.espn_overall_rank %></td>
        <td><%= player.espn_position_rank %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => @player.name.titleize %></h1>
</div>

<div class="row">
  <div class="span1">
    <%= image_tag @player.photo_url %>
  </div>

  <div class="span11">
    <div style="font-size:24px">
    <%= @player.position %> | <%= @player.height %>, <%= @player.weight %> | <%= @player.college %>
    </div>

    <br>
    <div class="pull-left">
      <strong><%= model_class.human_attribute_name(:hometown) %>:</strong>
      <%= @player.hometown %><br>
      <strong><%= model_class.human_attribute_name(:college_class) %>:</strong>
      <%= @player.college_class %><br>
      <strong><%= model_class.human_attribute_name(:date_of_birth) %>:</strong>
      <%= @player.date_of_birth %><br>
      <strong><%= model_class.human_attribute_name(:age) %>:</strong>
      <%= @player.age %>
    </div>

    <div class="pull-left offset1">
      <strong><%= model_class.human_attribute_name(:reach) %>:</strong>
      <%= @player.reach %><br>
      <strong><%= model_class.human_attribute_name(:wingspan) %>:</strong>
      <%= @player.wingspan %><br>
      <strong><%= model_class.human_attribute_name(:espn_overall_rank) %>:</strong>
      <%= @player.espn_overall_rank %><br>
      <strong><%= model_class.human_attribute_name(:espn_position_rank) %>:</strong>
      <%= @player.espn_position_rank %>
    </div>

  </div>
</div>

<br>
<div class="row">
<div class="sentiment span4">
  <h3>Sentiment Summary</h3>
  <table class="table" style="font-size:20px;">
    <tr>
      <td>In the News: </td>
      <td style="color:<%=@player.get_color(@player.news_sentiment)%>"> <%= @player.get_sign(@player.news_sentiment) %><%= @player.news_sentiment.round(2) %></td>
      <td>Rank: </td>
      <td><%= @player.news_sentiment_rank %></td>
    </tr>
    <tr>
      <td>On Twitter: </td>
      <td style="color:<%=@player.get_color(@player.tweet_about_sentiment)%>"> <%= @player.get_sign(@player.tweet_about_sentiment) %><%= @player.tweet_about_sentiment.round(2) %></td>
      <td>Rank: </td>
      <td><%= @player.tweet_about_sentiment_rank %></td>
    </tr>
    <tr>
      <td>His Twitter: </td>
      <td style="color:<%=@player.get_color(@player.tweet_sentiment)%>"> <%= @player.get_sign(@player.tweet_sentiment) %><%= @player.tweet_sentiment.round(2) %></td>
      <td>Rank: </td>
      <td><%= @player.tweet_sentiment_rank %></td>
    </tr>
  </table>
</div>

<div class="keywords span8">
  <h3>Keywords in the News</h3>
  <div class="pull-left">
  <% if @player.keyword_array != nil %>
  <% @player.keyword_array[0...10].each_with_index do |keyword, i| %>
    <%=i+1%>. <%=keyword[0]%><br>
  <% end %>
  <% end %>
  </div>
  <% if @player.keyword_array.count > 10 %>
  <div class="pull-left" style="padding-left:30px;">
  <% @player.keyword_array[10...20].each_with_index do |keyword, i| %>
    <%=i+11%>. <%=keyword[0]%><br>
  <% end %>
  </div>
  <% end %>
</div>
</div>

<div class="articles">
    <h3>News</h3>
    <table>
      <tbody>
      <% @news.each do |news| %>
          <tr>
            <td valign="top">
              <strong><%=news.title%></strong><br>
              <a href="<%=news.url%>"><%=news.url%></a><br>
              <%=news.description%><br><br>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table> 
</div>

<div class="row">
<div class="tweets span6">
    <h3>Tweets</h3>
    <table>
      <tbody>
      <% @tweets.each do |tweet| %>
          <tr>
            <td valign="top">
              <strong>@<%=@player.twitter_handle%>: </strong><%=tweet.text%><br><br>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table> 
</div>

<div class="tweets_about span6">
    <h3>Tweets About</h3>
    <table>
      <tbody>
      <% @tweet_abouts.each do |tweet| %>
          <tr>
            <td valign="top">
              <strong>@<%=tweet.tweeted_by%></strong>: <%=tweet.text%><br><br>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table> 
</div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              player_path(@player),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>